### ISSUE TITLE
Hoodie Server version needs updating

### ISSUE THREAD

**Issue by Charlotteis** [zoepage/hoodie-moufle#8]
Hello!

I'm just going through the map app tutorial (which uses this boilerplate) on hood.ie and am encountering the following error when I run `hoodie start`:

```
Version: 0.6.3 (node v0.12.2, npm 2.10.0, platform: darwin)

util.js:634
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:634:43)
    at Object.<anonymous> (/Users/charlotteis/code/hoodietut/HoodieMaps/node_modules/hoodie-server/node_modules/http-proxy/lib/http-proxy/index.js:111:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/charlotteis/code/hoodietut/HoodieMaps/node_modules/hoodie-server/node_modules/http-proxy/lib/http-proxy.js:4:17)
    at Module._compile (module.js:460:26)
```

The dependency in this project for hoodie-server is `0.9.19` but the latest version is now `3.1.1`.
Updating the dependency in `package.json` and running `npm install` seemed to fix this error but I wasn't sure if this project required the version of `hoodie-server` you set so I'm posting an issue rather than submitting a PR this time.

Hope this helps! :)

**Comment by zoepage** [comment]
Thanks for pointing that out! :)
You can send a PR. Would be great. 

<3

**Comment by Charlotteis** [comment]
Done!

**Comment by zoepage** [comment]
thank youuuuu!
